# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: False

# Setup
title:               George Wildridge
tagline:             
description:         'I am an aspiring student within the field of machine learning'
url:                 #http://georgewildridge.github.io/
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              George Wildridge
  url:               https://twitter.com/georgewildridge
  email:             

# Custom vars
version:             
